### ISSUE TITLE
About "kernel.pid_max" and "fs.file-max"

### ISSUE THREAD

**Issue by IceCodeNew** [k4yt3x/sysctl#2]
I found this file shipped with Ubuntu Focal.
```
* Applying /usr/lib/sysctl.d/50-pid-max.conf ...
kernel.pid_max = 4194304
```

It seems like if we configure this parameter here like:
https://github.com/k4yt3x/sysctl/blob/abb9f9fc22fe18cb128322c801460ec75d9935c8/sysctl.conf#L57-L58
, we are actually **decrease** the max allowed PID rather than `allow for more PIDs`

---

Related PR: #3

**Comment by k4yt3x** [comment]
Thanks that's interesting. I'll do some more researches and determine the best course of action.

**Comment by k4yt3x** [comment]
Like you said, the default `kernel.pid_max` appears to be `4194304`. Following that logic, I've also checked the `fs.file-max`, which appears to be `9223372036854775807`, larger than what's in this repo. I will do some more researches to determine if it's the best to increase the value in this config or is it best to comment it out and leave it to the OS default.

**Comment by k4yt3x** [comment]
After doing some researches, here are my conclusions:

- On a 32-bit system, this value can be maxed out to 2^15=`32768`
- On a 64-bit system, this value can be maxed out to 2^22=`4194304`

**Comment by k4yt3x** [comment]
The `fs.file-max` can get up to:
- 2147483647 (0x7fffffff) on a 32-bit system
- 9223372036854775807 (0x7fffffffffffffff) on a 64-bit system

**Comment by k4yt3x** [comment]
I think I'll update the config with the recommended values on 64-bit systems.

**Comment by k4yt3x** [comment]
Done. Please check https://github.com/k4yt3x/sysctl/commit/2f4267a8d9870aab65898987a32c08b13a6ff45a
